apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flow-monitoring
  labels:
    app: api-flow-monitoring
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: api-flow-monitoring
  template:
    metadata:
      labels:
        app: api-flow-monitoring
    spec:
      containers:
      - name: api-flow-monitoring
        image: apiflowmonitor:latest 
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "production" 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-flow-monitoring-service
spec:
  selector:
    app: api-flow-monitoring
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080  
  type: LoadBalancer  


# kubectl apply -f api-transaction-monitoring-deployment.yaml
